---
- name: Check if postgresql is installed
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' 'postgresql' | grep -v '^$'
  register: postgresql_server_register_version
  check_mode: no
  changed_when: False
  failed_when: False

# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: open port for postgres
  ufw:
    rule: allow
    port: 5432
    proto: tcp
    src: "{{ item }}/32"
  with_items:
    - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
    - "{{ groups['postgresql'] }}"
    - "{{ groups['radius'] }}"

- include_tasks: pg_partman.yml

- include_tasks: initialize.yml
- include_tasks: configure.yml

- include: "{{ postgresrep_role }}.yml"
  when: postgresrep_role != 'skip'

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes

# Configure PostgreSQL.
- import_tasks: users.yml
  when: postgresrep_role != 'slave'

- import_tasks: databases.yml
  when: postgresrep_role != 'slave'


