---
- name: Ensure PostgreSQL priv.
  postgresql_privs:
    db: "{{ item.db }}"
    privs: "{{ item.privs | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
    roles: "{{ item.roles }}"
    grant_option: "{{ item.grant_option | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    login: "{{ item.login | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_privilegies }}"
  no_log: true
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true