---
- name: create gitlab container
  docker_container:
    name: gitlab
    hostname: gitlab.example.com
    image: gitlab/gitlab-ee:latest    
    state: started
    restart_policy: always
    published_ports:
      - "443:443"
      - "80:80"
      - "2222:22"
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitla
      - /srv/gitlab/data:/var/opt/gitlab