---
- name: Copy ssl cert for gitlab
  copy:
    src: ssl
    dest: /srv

- name: Copy site configuration
  template:
    src: gitlab-compose.yml
    dest: ~/docker-compose.yml

- name: build and start docker containers
  docker_service:
    project_src: /root
    build: yes
    restarted: true

- name: cron for backup gitlab
  cron:
    name: "gitlab backup"
    minute: "0"
    hour: "0"
    job: "docker exec -t root_web_1 gitlab-rake gitlab:backup:create DIRECTORY=gitlab"