---
- name: add nginx repo
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present
    update_cache: true

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: copy nginx configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
      src: 'nginx.conf',
      dest: '/etc/nginx/nginx.conf'
    }
    - {
      src: 'expires.conf',
      dest: '/etc/nginx/expires.conf'
    }
  notify: restart nginx

- name: unlink default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    force: true
  notify: restart nginx

- name: enable nginx
  systemd:
    enabled: true
    name: nginx

- name: copy nginx configs
  template:
    src: 'nginx.host.j2'
    dest: '/etc/nginx/sites-available/{{ item.value.url }}.conf'
  with_dict: "{{ virtualhost }}"
  register: change_conf
  notify: restart nginx
  when: virtualhost is defined
#  no_log: true

- name: link nginx config
  file:
    src: '/etc/nginx/sites-available/{{ item.value.url }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item.value.url }}.conf'
    state: link
    force: yes
  with_dict: "{{ virtualhost }}"
  notify: restart nginx
  no_log: true
  when: virtualhost is defined
