---
zabbix_user: Admin
zabbix_pass: gonQuancajes
zabbix_URL: http://zabbix.gw.lan
zabbix_server: zabbix.gw.lan
zabbix_linux_template: 'Template OS Linux'
zabbix_nginx_template: Template_Nginx
zabbix_netstat_template: 'Template TCP Stats'
zabbix_smartctl_template: 'Template_HDD_SMARTMONTOOLS_2_WITH_LLD'
zabbix_mysql_template: 'Template App MySQL'
zabbix_mysql_slave_template: 'Template_MySQL_Slave'
zabbix_mysql_pass: 'Vy8XKARa3sqivR'
zabbix_bindir: /usr/sbin/zabbix_agentd
zabbix_apt_url: https://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+{{ ansible_distribution_release }}_all.deb
nginx: 0
netstat: 1
smartctl: 0
mysql: 0
mysql_slave: 0
zabbix_script_directory: '/usr/lib/zabbix/externalscripts'
zabbix_conf_directory: '/etc/zabbix/zabbix_agentd.d'
another_port: false
zabbix_port: 10050