- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s

  # Nginx hosts
  hosts: ["http://127.0.0.1:10061/nginx_status"]

  # Path to server status. Default server-status
  server_status_path: "server-status"