---
radius_conf: "{{ inventory_dir }}/group_vars/radius/vault.yml"
radius_server: "{{ groups['radius'][0] }}"

softether_srcdir: vpnserver
softether_bindir: /usr/local
softether_source_url: https://ams3.digitaloceanspaces.com/gettwifi-src/softether-vpnserver-v4.27-9668-beta-2018.05.29-linux-x64-64bit.tar.gz

softether_config:
  - src: 'vpn_server.config'
    dest: '{{ softether_bindir }}/{{ softether_srcdir }}/vpn_server.config'

softether_template:
  - src: 'vpnserver.service'
    dest: '/lib/systemd/system/vpnserver.service'
  - src: 'tap.yaml'
    dest: '/etc/netplan/tap.yaml'

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
  - rule: 'allow'
    port: 443
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 500
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 4500
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 1701
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 10050
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 80
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
      - 172.20.0.0/16
  - rule: 'allow'
    port: 9200
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
      - 172.20.0.0/16
  - rule: 'allow'
    port: 5432
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
      - 172.20.0.0/16
  - rule: 'allow'
    port: 37008
    proto: 'udp'
    from_ip:
      - 10.135.0.0/16
      - 172.20.0.0/16
  - rule: 'allow'
    port: 6379
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
      - 172.20.0.0/16
  - rule: 'allow'
    port: 5044
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
      - 172.20.0.0/16

sniffr_dir: /var/www/sniffr
sniffr_port: 37008
sniffr_pass: 123456
sniffr_user: web
sniffr_group: sniffr

local_user:
  - name: "{{ sniffr_user }}"
    group: "{{ sniffr_group }}"
    password: 1128256asdf
    password_lock: yes
    home: /opt/www
    shell: /bin/bash
    groups:
      - sniffr
      - "{{ sniffr_group }}"
    allow_key:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZhRbftUDYmMGr3+YNWPD2Wfuo/suQ0OyUv/URW9Yb0/yiW2WZg6zNFLnQPklcLbWceOcctKnD78JatLAlGvcDcN/3SxG7jZQItRjFxQtBC6NnRrTq1pbL12zWpW7aUX8igpngcEDr9uKhuVV5bWwSzaVin1IZMGZsVLOu/Yg+cmnC7MaRrHXWf51pVRekdzgJCxNmdzuVr8FUDzY/N3CcBAVKRlP7ZbpfCHqXnzvEqINM3x4pkkHgCdEJ0q7Zf6j98cLNMAFPTnd2EVFt3RH8MO2DsbFArAvXXdAhTFjehEgp9/XRLHYKwgklL7+m8oLkqY+uG4xr49htOUe27P3B root@kali'

monit_template:
  - dir: conf-available
    link: 'conf-enabled'
    template:
      - src: 'monit-sniffr.conf'
        dest: 'sniffr.conf'

sniffr_template:
  - src: 'sniffr.sh.j2'
    dest: '{{ sniffr_dir }}/sniffr.sh'
    mode: '0770'
    owner: "{{ sniffr_user }}"
    group: "{{ sniffr_group }}"
  - src: 'sniffr'
    dest: '/etc/logrotate.d/sniffr'
    mode: '0644'
    owner: root
    group: root