---
- name: Install haproxy
  apt:
    name: haproxy
    update_cache: true

- name: Copy haproxy configuration
  template:
    src: "{{ haproxy_config }}"
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: enable haproxy
  systemd:
    enabled: true
    name: haproxy
