---
cassandra_bindir: /usr/sbin/cassandra
cassandra_repository: "deb http://www.apache.org/dist/cassandra/debian 311x main"
cassandra_key:
  - keyserver: "pool.sks-keyservers.net"
    id: "A278B781FE4B2BDA"
cassandra_config_path: /etc/cassandra/cassandra.yaml
cassandra_cluster_name: gettwifi_cluster
cassandra_recriate_cluster: false
cassandra_update_password: false
cassandra_pass: 'ienecieY1pee7Aep'
user_pass: 'tie8lae5eeP2aith'
cassandra_global_config_options:
  - option: cluster_name
    value: '{{ cassandra_cluster_name }}'
    regex: ''
    tab: ''
  - option: authenticator
    value: 'PasswordAuthenticator'
    regex: ''
    tab: ''
  - option: concurrent_reads
    value: '32'
    regex: ''
    tab: ''
  - option: concurrent_writes
    value: '64'
    regex: ''
    tab: ''
  - option: concurrent_counter_writes
    value: '32'
    regex: ''
    tab: ''
  - option: disk_optimization_strategy
    value: 'ssd'
    regex: ''
    tab: ''
  - option: memtable_allocation_type
    value: 'offheap_objects'
    regex: ''
    tab: ''
  - option: memtable_offheap_space_in_mb
    value: '256'
    regex: ''
    tab: ''
  - option: write_request_timeout_in_ms
    value: '3000'
    regex: ''
    tab: ''
  - option: memtable_flush_writers
    value: '{{ ansible_processor_vcpus }}'
    regex: ''
    tab: ''
  - option: '- seeds'
    value: "{{ lookup('flattened', groups['cassandra']) }}"
    regex: '.*'
    tab: '          '
  - option: listen_address
    value: '{{ inventory_hostname }}'
    regex: ''
    tab: ''
  - option: rpc_address
    value: '{{ inventory_hostname }}'
    regex: ''
    tab: ''
  - option: endpoint_snitch
    value: 'GossipingPropertyFileSnitch'
    regex: ''
    tab: ''
  - option: auto_bootstrap
    value: 'false'
    regex: ''
    tab: ''