---
- name: restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart apache2
  service: name=apache2 state=restarted enabled=yes

- name: restart mariadb
  service: name=mysql state=restarted enabled=yes