---
- name: restart filebeat
  systemd:
      state: restarted
      enabled: yes
      name: filebeat

- name: restart metricbeat
  systemd:
      state: restarted
      enabled: yes
      name: metricbeat