---
- name: Install common programm
  apt:
    name: libpng-dev
    update_cache: yes
    cache_valid_time: 3600

- name: create folder for dhparam
  file:
    path: /etc/nginx/ssl/
    state: directory
    mode: 0775

- name: create dhparam
  openssl_dhparam:
    path: /etc/nginx/ssl/dhparams.pem
    size: 2048
  notify: restart nginx

- name: copy nginx configs
  template:
    src: 'nginx.host.j2'
    dest: '/etc/nginx/sites-available/{{ item.value.url }}.conf'
  with_dict: "{{ virtualhost }}"
  register: change_conf
  notify: restart nginx
#  no_log: true

- name: link nginx config
  file:
    src: '/etc/nginx/sites-available/{{ item.value.url }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item.value.url }}.conf'
    state: link
    force: yes
  with_dict: "{{ virtualhost }}"
  notify: restart nginx
  register: letsencrypt_cert
  no_log: true

#- name: Check if certificate already exists.
#  stat:
#    path: /etc/letsencrypt/live/{{ item.value.url }}/fullchain.pem
#  register: letsencrypt_cert
#  with_dict: "{{ virtualhost }}"

- name: Generate new certificate if one doesn't exist.
  shell: certbot certonly --standalone --noninteractive --agree-tos \
           --email {{ certbot_admin_email | default('mak@gettwifi.com') }} \
           -d {{ item.value.url }}
  with_dict: "{{ virtualhost }}"
  # when: letsencrypt_cert is changed


- name: validate nginx conf
  command: nginx -t
  changed_when: false
  when: change_conf is changed