#image: docker:stable
#
#variables:
#  DOCKER_DRIVER: overlay2
#
#before_script:
#- docker info

stages:
  - test
  - build
  - pp
  - prod
  - docker-push-image

variables:
  REGISTRY_BASE: ${CI_REGISTRY}/${CI_PROJECT_PATH_SLUG}

lint:
  image: particlekit/ansible-lint
  stage: test
  script:
      - ansible-lint all.yml

build:
  stage: build
  script:
      - echo "build"
      - echo $CI_PROJECT_NAMESPACE
      - echo $CI_PROJECT_PATH
      - echo $CI_PROJECT_NAME
      - echo $CI_REGISTRY_IMAGE

deploy to preprod:
  stage: pp
  when: on_success
  script:
    - echo "deploy to preprod"
  except:
    - master


deploy to prod:
  stage: prod
#  when: manual
  when: on_success
  script:
    - echo "deploy to prod"
  allow_failure: false
  only:
    - master

build_image:
  allow_failure: true
  image: docker:stable
  stage: docker-push-image
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:build .
    - docker tag $CI_REGISTRY_IMAGE:build $REGISTRY_BASE:build
    - docker push $CI_REGISTRY_IMAGE:build
  only:
    changes:
      - Dockerfile
#  except:
#    - tags
#    - branches
