- hosts: elastic_nodes
  become: true
  roles:
    - common
    - ufw
    - elasticsearch

- hosts: elastic_kibana
  become: true
  roles:
    - common
    - ufw
    - elasticsearch
    - kibana
    - nginx
