---
- name: softether server
  hosts: softether
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - common
    - ufw
    - softether
    - user
    - monit
    - haproxy
    - sniffr
    - zabbix