---
- name: stage server
  hosts: stage
  become: yes
  become_method: sudo
  become_user: root

  roles:
#    - common
#    - ufw
#    - user
#    - postgresql
#    - docker
#    - elk
#    - nginx
#    - zabbix
#    - sniffr
#    - elasticsearch
#    - kibana
#    - zabbix
    - common
    - ufw
    - user
    - nginx
    - nodejs