---
- name: Workstation for developers
  hosts: my
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - common
    - ufw
    - { role: ansible-role-openvpn-master, clients: [client1, client2]}