---
- name: test server
  hosts: test
  become: yes
  become_method: sudo
  become_user: root
#  serial: 1

  roles:
#    - common
#    - asterisk
#    - common
#    - ufw
#    - user
##    - postgresql
#    - monit
#    - haproxy
#    - sniffr
#    - zabbix
#    - s3cmd
#    - web_ruby
#    - dns
    - common
    - ufw
    - softether
    - user
