---
- name: test server
  hosts: test
  become: yes
  become_method: sudo
  become_user: root
  serial: 1

  roles:
    - common
    - ufw
    - user
#    - postgresql
#    - monit
#    - zabbix
#    - s3cmd
    - web_ruby