---
- name: Workstation for developers
  hosts: test
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - DO_space
#    - consul
#    - docker
#    - common
#    - nomad
#    - swarm