---
- name: web server
  hosts: web
  become: yes
  become_method: sudo
  become_user: root

  roles:
#    - common
    - ufw
    - user
    - rvm
    - nodejs
#    - passenger
    - monit
    - web_ruby
    - zabbix
