---
- name: set password for user root
  user:
    name: root
    password: "{{password | password_hash('sha512', 'mysecretsalt')}}"

- name: create local user
  include_tasks: user.yml
  when: local_user is defined