---
- name: check exist terraform
  stat:
    path: "{{ bin_dir }}/terraform"
  changed_when: False
  failed_when: False
  register: terraform_available

- name: Download and unarchive a terraform
  unarchive:
    src: "{{ terraform_source_url }}"
    dest: "{{ bin_dir }}"
    remote_src: yes

- name: check exist packer
  stat:
    path: "{{ bin_dir }}/packer"
  changed_when: False
  failed_when: False
  register: packer_available

- name: Download and unarchive a packer
  unarchive:
    src: "{{ packer_source_url }}"
    dest: "{{ bin_dir }}"
    remote_src: yes