---
- name: include java role
  include_role:
    name: java

- name: check exist phpstorm
  stat: path=/opt/phpstorm/
  register: phpstorm_available

- name: Download source phpstorm
  get_url:
    url: https://download-cf.jetbrains.com/webide/PhpStorm-2017.2.4.tar.gz
    dest: /tmp/PhpStorm.tar.gz
    mode: 0755
  when: phpstorm_available.stat.exists == false

- name: extract phpstorm archive
  unarchive:
    src: /tmp/PhpStorm.tar.gz
    dest: /tmp/
    copy: no
  when: phpstorm_available.stat.exists == false

- name: mv phpstorm to work dir
  command: mv /tmp/PhpStorm-172.4155.41/ /opt/phpstorm/
  when: phpstorm_available.stat.exists == false

- name: link phpstorm
  file:
    src: /opt/phpstorm/bin/phpstorm.sh
    dest: /usr/local/bin/phpstorm
    state: link
    force: yes