---
- name: restart redis-server
  systemd:
    name: redis-server
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart redis-sentinel
  systemd:
    name: redis-sentinel
    state: restarted
    enabled: true
    daemon_reload: true
