---
- name: restart redis-server
  systemd:
    name: redis-server
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart redis-sentinel
  systemd:
    name: redis-sentinel
    state: restarted
    enabled: yes
    daemon_reload: yes