---
root_ssh:
  - name: ansible
    publish_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDADO9BxJI7Cxkl06aw7MB5i91u3qKhrNOKPQTfDSMswEURAsSaHL7xfTLgYI85vhfJWbp481GJ4wjvMRthaxXx8hJcoSFiTJZnWnci8Mzby6gCOB/z02tN+fl/U0axY489pHXB84P3oOHh95qWm98GaG8EtKMsqbMURD2ywQ97U5d4ETft4fEh5paX4bL261M3SGJSoGPrfpXJ1Bsm/GX3zEkXbYksSzRb40kNSl+ImIpVr9vU+fQZJ3thYks1FzFLUENwkML/hMztJas6kP3yEvDI0M3R1jGnW7XGIkXwA5VP4vJG2q/8vnF8EqTmKyAKqVdCfofPHQ0D+XMygGdz ansible@gettwifi.com
  - name: makovsky
    publish_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRSsBepZh7W+DhmFX56lUqrqBjUbnqjks3phcJa1eq9pdg8e9LCkQzdGiHbYAb2CacKWsa79Sb2lhAOmFkMAHSrpqFNSGl+KB/UKx8W86lMVvplXUSDqEwxqXT6O3vK9BOApQMyubH2aEMRn1yrYXyRxrcwxzrOjBDIAkr28jKylTr5GfPnUnZvmGyFxkR/7Ws5ZjfV8wiGh+styBJavsqXRaW9ihQ/paOzsrgupw9KjSFQd2TfeZ8JFydj4Ac3t2/xyYGhnqw9O8XuOZed2ni7JQGi9Cj0ENcYf0Ps0dCYjotAGdLI/6P6rZDMIak8sqlv8fGrFJ5Yhy9DDH/d5eD user@DESKTOP-A0CFRML
  - name: gribanov
    publish_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZhRbftUDYmMGr3+YNWPD2Wfuo/suQ0OyUv/URW9Yb0/yiW2WZg6zNFLnQPklcLbWceOcctKnD78JatLAlGvcDcN/3SxG7jZQItRjFxQtBC6NnRrTq1pbL12zWpW7aUX8igpngcEDr9uKhuVV5bWwSzaVin1IZMGZsVLOu/Yg+cmnC7MaRrHXWf51pVRekdzgJCxNmdzuVr8FUDzY/N3CcBAVKRlP7ZbpfCHqXnzvEqINM3x4pkkHgCdEJ0q7Zf6j98cLNMAFPTnd2EVFt3RH8MO2DsbFArAvXXdAhTFjehEgp9/XRLHYKwgklL7+m8oLkqY+uG4xr49htOUe27P3B root@kali
  - name: gribanov2
    publish_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDenOYTsF4V3K+foiwzbrsPpsWoc1frEDAs/QB+J5w7r562rjK/rjjq7BOWAUZN6iQmFvaN+qBfQTEMEEFaB6il6mxiZMoT1TPCzIh5ZZAqw+Gc6+UeRklmAFy+QOZcv8C92SoHaqSdidN5HRcr/Qf+vO56w3Mdelc5KBajf8hFwM8YqHUV60Plgezz2AOD09bpZwNgaUuuBMj2TzPscZHLGglafbsZY4E/+0zJTSXV2T51pEqX3oUYHK4xgU/MR+l5ZaGxAf6t1aV0kyUVsOSWcblz8ZUgxJ/MJrwtgDPxwEsLuf09neEMw3pSP8MFeLcTa5PnrjOFvimarW3SbO1v u10101@u10101-MS-7751
  - name: spark
    publish_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDphZtHMD/gDYr1g9s+iQ9TKjNup16ZxcBq+vQlJbX/I7gTW8YBx57414obUhwSojEsrHtiXGZbiQbxTBJGs+ihzA7zqWGZS7UeNH+OplRnnYf1tSqGPojUcovnQSYmsnZ5KF2E6xliYLmX85oeSjOyi4WIEq9DblcEQRvDpWnqu5MBCV9kjeeguUXb7owzJks+kSXwlKmbJuXx8YpdHHvsnYuYz0KY8mP66weQb0axajpDOfjUvp4tLJMnB4pQj7FrKSQbjbei5YeMtWwr+TGzruA7HwG1lOZESmRId6HQfMhwqVzEhhn2bgn5s9E+yd2M76SjIebltjilyAMuYqq1 spark@gettwifi.com

cassandra_cluster_name: gettwifi_cluster
cassandra_global_config_options:
  - option: cluster_name
    value: '{{ cassandra_cluster_name }}'
    regex: ''
    tab: ''
  - option: authenticator
    value: 'PasswordAuthenticator'
    regex: ''
    tab: ''
  - option: concurrent_reads
    value: '32'
    regex: ''
    tab: ''
  - option: concurrent_writes
    value: '64'
    regex: ''
    tab: ''
  - option: concurrent_counter_writes
    value: '32'
    regex: ''
    tab: ''
  - option: disk_optimization_strategy
    value: 'ssd'
    regex: ''
    tab: ''
  - option: memtable_allocation_type
    value: 'offheap_objects'
    regex: ''
    tab: ''
  - option: memtable_offheap_space_in_mb
    value: '256'
    regex: ''
    tab: ''
  - option: write_request_timeout_in_ms
    value: '3000'
    regex: ''
    tab: ''
  - option: memtable_flush_writers
    value: '{{ ansible_processor_vcpus }}'
    regex: ''
    tab: ''
  - option: '- seeds'
    value: "{{ lookup('flattened', [groups['cassandra'] | map('extract',hostvars,'ansible_ssh_host') | list])}}"
    regex: '.*'
    tab: '          '
  - option: listen_address
    value: '{{ ansible_ssh_host }}'
    regex: ''
    tab: ''
  - option: rpc_address
    value: '0.0.0.0'
    regex: ''
    tab: ''
  - option: broadcast_rpc_address
    value: '{{ ansible_ssh_host }}'
    regex: ''
    tab: ''
  - option: endpoint_snitch
    value: 'GossipingPropertyFileSnitch'
    regex: ''
    tab: ''
  - option: auto_bootstrap
    value: 'false'
    regex: ''
    tab: ''

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 7000
    proto: 'tcp'
    from_ip: "{{ [groups['cassandra'] | map('extract',hostvars,'ansible_ssh_host') | list, hostvars[groups['openvpn'][0]].private_ip]|flatten }}"
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 9042
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 10050
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 7199
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 20004
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 20000
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 20001
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 20002
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 20003
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 20005
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 8081
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"