---
- name: Include postgresql vars files
  include_vars:
    file: "{{ postgrs_conf }}"
    name: postgresql

- name: add radius repo
  apt_repository:
    repo: 'ppa:freeradius/stable-3.0'
    state: present
    update_cache: True

- name: Install radius
  apt:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  with_items:
    - 'freeradius=3.0.15-ppa1~xenial'
    - 'freeradius-postgresql'
  register: installed

- name: fix broken dependences
  block:
    - replace:
        path: /var/lib/dpkg/info/freeradius-postgresql.postinst
        regexp: 'force-reload'
        replace: 'restart'

    - shell: dpkg --configure -a
  when: installed.failed is defined

#- debug:
#    msg: "{{ radius_template }}"

- name: Copy freeradius template
  template:
    src: "{{ item.0.dir }}/{{ item.1.src }}"
    dest: "{{ radius_config_dir }}/{{ item.0.dir }}/{{ item.1.dest }}"
  with_subelements:
    - "{{ radius_template | selectattr('template', 'defined') | list }}"
    - template
  notify: restart freeradius

- name: Copy freeradius file config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ radius_file }}"
  notify: restart freeradius

- name: link freeradius configs
  file:
    src: "{{ radius_config_dir }}/{{ item.0.dir }}/{{ item.1.dest }}"
    dest: "{{ radius_config_dir }}/{{ item.0.link }}/{{ item.1.dest }}"
    state: link
    force: yes
  with_subelements:
    - "{{ radius_template | selectattr('template', 'defined') | list }}"
    - template
  when: item.0.link is defined
  notify: restart freeradius

- name: unlink default config
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  with_items: "{{ unlink_config }}"
  notify: restart freeradius

- name: radius configure global settings.
  lineinfile:
    dest: "/etc/freeradius/radiusd.conf"
    regexp: "^\t{{ item.option }}\\s.+$"
    line: "\t{{ item.option }} = {{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ freeradius_config_options }}"
  notify: restart freeradius

- name: radius include global settings.
  replace:
    path: "/etc/freeradius/radiusd.conf"
    regexp: "^{{ item.option }}.+$"
    replace: "{{ item.value }}"
  with_items: "{{ freeradius_include_options }}"
  notify: restart freeradius