---
- name: add radius repo
  apt_repository:
    repo: 'ppa:freeradius/stable-3.0'
    state: present
    update_cache: True

- name: Install radius
  apt:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  with_items:
    - 'freeradius=3.0.15-ppa1~xenial'
    - 'freeradius-postgresql'
  register: installed

- debug:
    msg: "{{ installed }}"

- replace:
    path: /var/lib/dpkg/info/freeradius-postgresql.postinst
    regexp: 'force-reload'
    replace: 'restart'
  when: installed.failed is defined

- shell: dpkg --configure -a
  when: installed.failed is defined

- name: Copy freeradius template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ radius_template }}"
  notify: restart freeradius

- name: Copy freeradius config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ radius_file }}"
  notify: restart freeradius

- name: link freeradius config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ link_config }}"
  notify: restart freeradius