---
- name: Include s3 vars files
  include_vars:
    file: "{{ s3_conf }}"
    name: s3

- name: Install s3cmd programm
  apt:
    name: s3cmd
    update_cache: true
    cache_valid_time: 3600

- name: Copy config file
  template:
    src: s3cfg.j2
    dest: ~/.s3cfg
