common: &common
  scope: 'user_birthday,email,user_friends,user_link,user_gender'
  # scope_without_post: 'user_birthday,email,user_friends,user_link,user_gender'
  extra_options:
    info_fields: 'name,email,birthday,devices,gender,link'
  embed_session_id: false
  auto_post: false
  app_id: '194150520733941'
  app_secret: 'abbde9c1b29941e5c3ec03db3308d52f'
  post:
    image_host: 'https://app.gettwifi.com'

development:
  <<: *common

production:
  <<: *common