common: &common
  scope: 'basic likes relationships'
  user_search:
    token: '{{ instagram_token }}'
  public_content:
    app_id: '{{ instagram_public_content_app_id }}'
    #app_secret: '0d7ac95dfef144f6aca1d74d339483e1'
  app_id: '{{ instagram_app_id }}'
  app_secret: '{{ instagram_app_secret }}'

development:
  <<: *common

production:
  <<: *common
