common: &common
  scope: 'r_basicprofile r_emailaddress w_share'
  app_id: '77xtop1b6q26kv'
  app_secret: 'QBSieYcMBkoyHPQ0'
  post:
    image_host: 'https://app.gettwifi.com'

development:
  <<: *common

production:
  <<: *common
