common: &common
  scope: 'r_basicprofile r_emailaddress w_share'
  app_id: '{{ linkedin_app_id }}'
  app_secret: '{{ linkedin_app_secret }}'
  post:
    image_host: '{{ post_image_host }}'

development:
  <<: *common

production:
  <<: *common
