common: &common
  scope: 'VALUABLE_ACCESS'
  embed_session_id: false
  app_id: '{{ odnoklassniki_app_id }}'
  app_secret: '{{ odnoklassniki_app_secret }}'
  upload_banner:
    token: '{{ odnoklassniki_token }}'
    group_id: '{{ odnoklassniki_group_id }}'
  extra_options:
    public_key: '{{ odnoklassniki_public_key }}'
  post:
    image_host: '{{ post_image_host }}'

development:
  <<: *common

production:
  <<: *common
