common: &common
  scope: 'user_birthday,email'
  embed_session_id: true
  app_id: 'rXry1eRF9AyBP25vskQ0g'
  app_secret: 'MoSfy6i9B4SdyLudCNLJFCjVZgPZ6UkQa8XapuuY7c'
  post:
    image_host: 'https://app.gettwifi.com'

development:
  <<: *common

production:
  <<: *common
