common: &common
  scope: 'user_birthday,email'
  embed_session_id: true
  app_id: '{{ twitter_app_id }}'
  app_secret: '{{ twitter_app_secret }}'
  post:
    image_host: '{{ post_image_host }}'

development:
  <<: *common

production:
  <<: *common
