common: &common
  scope: 'email,wall'
  scope_without_post: 'email'
  embed_session_id: true
  upload_banner:
    scope: 'email,wall,photos,offline'
    token: '{{ vkontakte_token }}'
    group_id: '{{ vkontakte_group_id }}'
  app_id: '{{ vkontakte_app_id }}'
  app_secret: '{{ vkontakte_app_secret }}'
  post:
    image_host: '{{ post_image_host }}'
    wall_post_api: true

development:
  <<: *common

production:
  <<: *common
