---
- - name: add repository for cassandra
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 311x main
    state: present

- name: add key for docker repositories
  apt_key:
    keyserver: "pool.sks-keyservers.net"
    id: "A278B781FE4B2BDA"
    state: present

- include_tasks: "java.yml"

- name: Install common
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - cassandra