---
- name: include java role
  include_role:
    name: java

- name: check exist cassandra
  stat:
    path: "{{ cassandra_bindir }}"
  changed_when: False
  failed_when: False
  register: cassandra_available

- name: add repository for cassandra
  apt_repository:
    repo: "{{ cassandra_repository }}"
    state: present

- name: add key for cassandra repositories
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.id }}"
    state: present
  with_items: "{{ cassandra_key }}"

- name: Install cassandra
  apt:
    name: "{{ item }}"
    update_cache: yes
#    state: latest
  with_items:
    - cassandra

- name: inithialize cluser
  block:
    - name: stop cassandra
      systemd:
        state: stopped
        name: cassandra

    - name: remove base
      file:
        path: /var/lib/cassandra/data/system/
        state: absent
        force: yes
  when: cassandra_recriate_cluster or cassandra_available.stat.exists == false

- name: Configure global settings.
  lineinfile:
    dest: "{{ cassandra_config_path }}"
    regexp: "^#?{{ item.regex }}{{ item.option }}.+$"
    line: "{{ item.tab }}{{ item.option }}: '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ cassandra_global_config_options }}"
  notify: restart cassandra

- name: ensure what  cassandra started
  systemd:
    state: started
    name: cassandra