---
ansible_user: root

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 53
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 53
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: "{{ zabbix_port }}"
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"

domain: gw.lan
rev_domain: 135.10.in-addr.arpa
host_name: ns1.{{ domain }}

list_public: true

records:
  local:
    ns1:
      forward: 10.135.62.157
      type: A
      last: 157.62
      rev: 135.10.in-addr.arpa
    zabbix:
      forward: 10.135.45.221
      type: A
      last: 221.45
      rev: 135.10.in-addr.arpa

  gettwifi:
    "@":
      forward: 10.135.74.65
      type: A
      last: 65.74
      rev: 135.10.in-addr.arpa

zones:
  local:
    name: gw.lan
  gettwifi:
    name: gitlab.gettwifi.com

private_ip: 10.135.62.157
private_interface: eth1

enable_local_dns: false