---
- name: Install programm for aws_s3
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
#    state: latest
  with_items:
    - python-boto
    - python-botocore
    - python-boto3
    - awscli

- name: copy file
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items: "{{ upload_files }}"

#- name: List objects in Space
#  aws_s3:
#    aws_access_key: "{{ spaces_access_key }}"
#    aws_secret_key: "{{ spaces_secret_key }}"
#    s3_url: "{{ spaces_endpoint }}"
#    bucket: "{{ space_name }}"
#    mode: list
#    rgw: true
#    encrypt: false
#  register: spaces_items

#- debug:
#    msg: "Contents of {{ space_name }}: {{ spaces_items.s3_keys }}"

- name: Simple PUT operation
  aws_s3:
    aws_access_key: "{{ spaces_access_key }}"
    aws_secret_key: "{{ spaces_secret_key }}"
    s3_url: "{{ spaces_endpoint }}"
    bucket: "{{ space_name }}"
    object: "/source/{{ item }}"
    src: "/tmp/{{ item }}"
    mode: put
    permission: public-read
    rgw: true
    encrypt: false
  with_items: "{{ upload_files }}"