---
ansible_user: vagrant
#ansible_become_pass: vagrant
enable_local_dns: false

rvm1_user: root
rvm1_install_path: /usr/local/rvm
rvm1_install_flags: '--auto-dotfiles'

create_user: true
local_user:
  - name: web
    group: www-data
    password: 1128256asdf
    password_lock: yes
    home: /opt/www
    shell: /bin/bash
    groups:
      - rvm

ufw_reset: true

ufw_rules:
  - policy: 'allow'
    direction: incoming

