---
- name: Include vault vars files
  include_vars:
    file: ../../files/vault_var.yml

- name: Install libhiredis-dev
  apt:
    name: libhiredis-dev
    update_cache: true

- name: create snifr config dir
  file:
    path: "{{ sniffr_dir }}/log"
    state: directory
    owner: "{{ sniffr_user }}"
    group: "{{ sniffr_group }}"
    mode: 0775

- name: Download and unarchive sniff
  unarchive:
    src: "{{ sniffr_source }}&private_token={{ gitlab_private_token }}"
    dest: "{{ sniffr_dir }}"
    remote_src: true
    owner: "{{ sniffr_user }}"
    group: "{{ sniffr_group }}"
    mode: 0775
  notify: restart sniffr

- name: copy sniffr scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ sniffr_template }}"
