---
xtra_dir: "xtrabackup"
backup_dir: "backup"
root_dir: "/root"
cron_hour: "4"
telegram_bot: "629640079:AAFS1CtMST9wDJ9XUkk0y3thN3aA1_p8B3o"

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 10051
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 80
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"