---
__postgresql_version: "10"
__postgresql_data_dir: "/var/lib/postgresql/{{ __postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"
__postgresql_daemon: postgresql
__postgresql_packages:
  - "postgresql-{{ __postgresql_version }}"
  - "postgresql-contrib-{{ __postgresql_version }}"
  - libpq-dev
  - "postgresql-server-dev-{{ __postgresql_version }}"
