---
- name: Update SSH configuration to be more secure.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
      regexp: "^PasswordAuthentication",
      line: "PasswordAuthentication no"
    }
    - {
      regexp: "^#ListenAddress 0.0.0.0",
      line: "ListenAddress {{ inventory_hostname }}"
    }
  notify: restart ssh