---
- name: Update SSH configuration to be more secure.
  replace:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  with_items:
    - {
      regexp: "^PasswordAuthentication yes",
      line: "PasswordAuthentication no"
    }
    - {
      regexp: "^#ListenAddress 0.0.0.0",
#      line: "ListenAddress {{ hostvars[inventory_hostname][interface_fact_var].ipv4.address }}"
      line: "ListenAddress {{ ansible_ssh_host }}"
    }
  notify: restart ssh