---
ansible_user: vagrant
private_interface: enp0s8
interface_fact_var: ansible_{{ private_interface }}

enable_local_dns: false
postgresql_users:
  - name: "{{ hotspot_user }}"
    password: "{{ hotspot_user_pass }}"
  - name: "{{ radius_user }}"
    password: "{{ radius_user_pass }}"

postgresql_databases:
  - name: hotspot
    owner: "{{ hotspot_user }}"
  - name: radius_users_mikrotik
    owner: "{{ radius_user }}"
  - name: radius_users_cisco
    owner: "{{ radius_user }}"
  - name: radius_users_chilli
    owner: "{{ radius_user }}"
  - name: radius_access_points
    owner: "{{ radius_user }}"



ufw_reset: true

ufw_rules:
  - policy: 'allow'
    direction: incoming

getbase_from_master: false

postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: listen_addresses
    value: '{{ hostvars[inventory_hostname][interface_fact_var].ipv4.address }}, localhost'
  - option: shared_buffers
    value: '{{ (ansible_memtotal_mb * 0.25)|int|abs }}MB'
  - option: max_connections
    value: '1000'
  - option: shared_preload_libraries
    value: 'pg_partman_bgw'
  - option: pg_partman_bgw.interval
    value: '3600'
  - option: pg_partman_bgw.dbname
    value: 'hotspot'
  - option: effective_io_concurrency
    value: '6'
  - option: seq_page_cost
    value: '1.0'
  - option: random_page_cost
    value: '2.0'

monit_template:
  - dir: conf-available
    link: 'conf-enabled'
    template:
      - src: 'monit-postgresql.conf'
        dest: 'postgresql.conf'