common: &common
  login: "{{ devinotelecom_login }}"
  password: "{{ devinotelecom_password }}"
  header: "TheKarma"
  #header: "TESTSMS"

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
