---
ansible_user: root

postgresql_users:
  - name: "{{ hotspot_user }}"
    password: "{{ hotspot_user_pass }}"
  - name: "{{ radius_user }}"
    password: "{{ radius_user_pass }}"

postgresql_databases:
  - name: hotspot
    owner: "{{ hotspot_user }}"
  - name: radius_users_mikrotik
    owner: "{{ radius_user }}"
  - name: radius_users_cisco
    owner: "{{ radius_user }}"
  - name: radius_users_chilli
    owner: "{{ radius_user }}"
  - name: radius_access_points
    owner: "{{ radius_user }}"

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 5432
    proto: 'tcp'
    from_ip: "{{ [groups['radius'], groups['postgresql'], hostvars[groups['openvpn'][0]].private_ip]|flatten }}"
    to_ip: "{{ inventory_hostname }}"
