common: &common
  adapter: postgresql
  encoding: utf-8
  host: "{{ postgres_server }}"
  timeout: 60

hotspot_common: &hotspot_common
  <<: *common
  username: "{{ postgresql_var.gw_hotspot_user }}"
  password: "{{ postgresql_var.gw_hotspot_user_pass }}"
  database: gw_hotspot
  pool: 10

radius_common: &radius_common
  <<: *common
  username: "{{ postgresql_var.gw_radius_user }}"
  password: "{{ postgresql_var.gw_radius_user_pass }}"
  pool: 5

development: # for rails c
  <<: *hotspot_common
production:
  <<: *hotspot_common

radius_development:
  <<: *radius_common
  database: gw_radius_users_mikrotik
radius_production:
  <<: *radius_common
  database: gw_radius_users_mikrotik

radius_cisco_development:
  <<: *radius_common
  database: gw_radius_users_cisco
radius_cisco_production:
  <<: *radius_common
  database: gw_radius_users_cisco

radius_chilli_development:
  <<: *radius_common
  database: gw_radius_users_chilli
radius_chilli_production:
  <<: *radius_common
  database: gw_radius_users_chilli

radius_ap_development:
  <<: *radius_common
  database: gw_radius_access_points
radius_ap_production:
  <<: *radius_common
  database: gw_radius_access_points