common: &common
  adapter: postgresql
  encoding: utf-8
  host: 127.0.0.1
  timeout: 60

hotspot_common: &hotspot_common
  <<: *common
  username: hotspot
  password: wv3vH3fOtKSd
  database: hotspot
  pool: 10

radius_common: &radius_common
  <<: *common
  username: radius
  password: mZph5AXJOsGv
  pool: 5

development: # for rails c
  <<: *hotspot_common
production:
  <<: *hotspot_common

radius_development:
  <<: *radius_common
  database: radius_users_mikrotik
radius_production:
  <<: *radius_common
  database: radius_users_mikrotik

radius_cisco_development:
  <<: *radius_common
  database: radius_users_cisco
radius_cisco_production:
  <<: *radius_common
  database: radius_users_cisco

radius_chilli_development:
  <<: *radius_common
  database: radius_users_chilli
radius_chilli_production:
  <<: *radius_common
  database: radius_users_chilli

radius_ap_development:
  <<: *radius_common
  database: radius_access_points
radius_ap_production:
  <<: *radius_common
  database: radius_access_points
