common: &common
  server: "{{ hostvars[groups['radius'][0]].private_ip }}"
  port: 17771
  acc_port: 17772
  secret: "{{ radius_var.radius_secret }}"

development:
  <<: *common

production:
  <<: *common
