sentinel: &sentinel
  sentinels:
  {% for item in groups['redis'] %}
  - :host: {{ hostvars[item].ansible_ssh_host }}
      :port: 26379
  {% endfor %}
    :role: :master

common: &common
  sidekiq:
    url: 'redis://mymaster/0'
    <<: *sentinel
  session:
    url: 'redis://mymaster/1'
    <<: *sentinel
  cache:
    url: 'redis://mymaster/2'
    <<: *sentinel
  mutex:
    url: 'redis://mymaster/3'
    <<: *sentinel
    pool:
      size: 16
      timeout: 2

development:
  <<: *common
production:
  <<: *common