---
- name: Install ufw
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - ufw

#- debug:
#    msg: "{{ hostvars[groups['openvpn'][0]] }}"

- name: open port for ssh
  ufw:
    rule: allow
    port: 22
    proto: tcp
    src: "{{ item }}"
  with_items:
    - "{{ hostvars[groups['openvpn'][0]].private_ip }}/32"
    - "{{ allow_ip }}"

- name: open ssh port for gitlab
  ufw:
    rule: allow
    port: 2222
    proto: tcp
    src: "{{ item }}"
  with_items:
    - "{{ hostvars[groups['openvpn'][0]].private_ip }}/32"
    - "{{ allow_ip }}"
  when: inventory_hostname == groups['gitlab'][0]

- name: Configure default incoming/outgoing rules with ufw.
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
    - { direction: outgoing, policy: allow }
    - { direction: incoming, policy: deny }