---
- name: check exist zabbix-server
  stat:
    path: "{{ zabbix_bindir }}"
  changed_when: False
  failed_when: False
  register: zabbix_available

- name: Download zabbix apt source
  get_url:
    url: "{{ zabbix_apt_url }}"
    dest: /tmp/zabbix.deb
    mode: 0740
  when: zabbix_available.stat.exists == false

- name: Install apt repo
  apt:
    deb: "/tmp/zabbix.deb"
  when: zabbix_available.stat.exists == false

- name: Install common
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - zabbix-server-mysql
    - zabbix-frontend-php
    - zabbix-agent

- name: Copy zabbix-server database dump
  copy:
    src: zabbix.gz
    dest: /tmp/zabbix.gz
  when: zabbix_available.stat.exists == false

- name: create database for zabbix
  mysql_db:
    name: "{{ zabbix_db_name }}"
    state: import
    target: /tmp/zabbix.gz
  when: zabbix_available.stat.exists == false

- name: create user for zabbix
  mysql_user:
    name: "{{ zabbix_db_user }}"
    host: localhost
    password: "{{ zabbix_db_pass }}"
    priv: "{{ zabbix_db_name }}.*:ALL"
    state: present

- name: edit zabbix-server config file
  lineinfile:
    backup: no
    path: /etc/zabbix/zabbix_server.conf
    regexp: "{{ item.path }}"
    line: "{{ item.regexp }}"
  with_items:
    - { path: 'DBHost=*', regexp: 'DBHost={{ zabbix_db_host }}' }
    - { path: 'DBName=*', regexp: 'DBName={{ zabbix_db_name }}' }
    - { path: 'DBUser=*', regexp: 'DBUser={{ zabbix_db_user }}' }
    - { path: 'DBPassword=*', regexp: 'DBPassword={{ zabbix_db_pass }}' }
  notify: restart zabbix-server

- name: edit apache2 config file
  lineinfile:
    backup: no
    path: /etc/apache2/conf-enabled/zabbix.conf
    regexp: "{{ item.path }}"
    line: "{{ item.regexp }}"
  with_items:
    - { path: 'Alias /zabbix*', regexp: '#Alias /zabbix /usr/share/zabbix' }
  notify: restart apache2

- name: copy mariadb config
  template:
    src: 'mysqld.cnf'
    dest: '/etc/mysql/conf.d/mariadb.cnf'
    force: yes
  notify: restart mariadb

- name: copy telegramm config
  template:
    src: 'telegram.sh'
    dest: '/usr/lib/zabbix/alertscripts/telegram.sh'
    force: yes
    owner: zabbix
    group: zabbix
    mode: 0760

- name: copy zabbix-server config
  template:
    src: 'zabbix.conf.php'
    dest: '/usr/share/zabbix/conf/zabbix.conf.php'
    force: yes

#- name: starte zabbix-server
#  systemd:
#    state: started
#    name: zabbix-server
#
#- name: enable zabbix-server
#  systemd:
#    enabled: yes
#    name: zabbix-server.service
- name: enable zabbix-server
  systemd:
    enabled: yes
    name: zabbix-server.service

- name: enable zabbix-client
  systemd:
    enabled: yes
    name: zabbix-agent.service

- name: starte zabbix-client
  systemd:
    state: started
    name: zabbix-agent

- name: copy nginx configs
  template:
    src: 'apache.conf'
    dest: '/etc/apache2/sites-available/000-default.conf'
    force: yes
  notify: restart apache2

- name: link nginx config
  file:
    src: '/etc/apache2/sites-available/000-default.conf'
    dest: '/etc/apache2/sites-enabled/000-default.conf'
    state: link
    force: yes
  notify: restart apache2