---
softether_srcdir: vpnserver
softether_bindir: /usr/local
softether_source_url: https://ams3.digitaloceanspaces.com/gettwifi/source/softether-vpnserver-v4.27-9668-beta-2018.05.29-linux-x64-64bit.tar.gz

softether_config:
  - src: 'vpn_server.config'
    dest: '{{ softether_bindir }}/{{ softether_srcdir }}'

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
  - rule: 'allow'
    port: 8443
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 500
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 4500
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 1701
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 10050
    proto: 'tcp'
    from_ip: "{{ groups['zabbix'] }}"
    to_ip: "{{ inventory_hostname }}"