---
#- debug:
#    msg: "{{ item }}"
#  with_dict: "{{ ruby_configs }}"
- name: Install common programm
  apt:
    name: libpq-dev
    update_cache: yes
    cache_valid_time: 3600

- name: '(Hack: keep SSH forwarding socket)'
  lineinfile:
      dest: /etc/sudoers
      insertafter: '^#?\s*Defaults\s+env_keep\b'
      line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'

- name: '(Hack: grant access to the socket to {{web_user}})'
  become: false
  acl: name='{{item}}' etype=user entity='{{web_user}}' permissions="rwx" state=present
  with_items:
      - "{{ ansible_env.SSH_AUTH_SOCK|dirname }}"
      - "{{ ansible_env.SSH_AUTH_SOCK }}"



- name: Clone project repositories
  git:
    repo: "git@{{ gitlab }}:{{ git_repo }}"
    dest: "{{ ruby_project_folder }}/shared"
    version: "{{ git_branch }}"
    force: yes
    accept_hostkey: yes
#    key_file: /home/{{ local_user }}/id_rsa
  become_user: "{{ web_user }}"
  become: yes
  register: cloned

- name: create web folder
  file:
    path: "{{ ruby_config_folders }}/{{ item.value }}"
    state: directory
    mode: 0775
  with_dict: "{{ ruby_configs }}"
  when: item.key == 'dir'
  become_user: "{{ web_user }}"
  become: yes

- name: Copy  template
  template:
    src: "{{ item.1.src }}"
    dest: "{{ ruby_config_folders }}/{{ item.0.dir }}/{{ item.1.dest }}"
  with_subelements:
    - "{{ ruby_configs | selectattr('template', 'defined') | list }}"
    - template