---
- name: Install common programm
  apt:
    name: "{{ bind_package }}"
    update_cache: true
    cache_valid_time: 3600

- name: Set hostname
  hostname:
    name: "{{ host_name }}"

- name: Set hostname fact
  set_fact:
    ansible_fqdn: "{{ host_name }}"

- name: edit bind9 systemctl config file
  lineinfile:
    backup: false
    path: /etc/default/bind9
    regexp: "{{ item.path }}"
    line: "{{ item.regexp }}"
  with_items:
    - { path: '^OPTIONS=*', regexp: 'OPTIONS="-4 -u bind"' }
  notify: restart bind9

- name: Copy named conf file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0660
    validate: 'named-checkconf %s'
  notify: restart bind9

- name: Copy named conf local file
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0660
    validate: 'named-checkconf %s'
  notify: restart bind9

- name: Make zones Directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Copy forward file
  template:
    src: db.forward.j2
    dest: /etc/bind/zones/db.{{ item.value.name }}
    owner: root
    group: bind
    mode: 0640
  with_dict:
    - "{{ zones }}"
  notify: restart bind9
# validate: "named-checkzone /etc/bind/zones/db.{{ item.value.name }} %s"


- name: Copy reverse file
  template:
    src: db.reverse.j2
    dest: /etc/bind/zones/db.{{ rev_domain }}
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9
# validate: "named-checkzone /etc/bind/zones/db.{{ rev_domain }} %s"
