---
ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 4040
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 8080
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: "7077"
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 10050
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
  - rule: 'allow'
    port: 20002
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"
