---
del_config: []
#del_config:
#  - pjsip.conf
#  - queues.conf
#  - indications.conf
#  - confbridge.conf
#  - voicemail.conf
#  - musiconhold.conf

asterisk_folders:
  - /var/lib/asterisk
  - /var/log/asterisk
  - /var/run/asterisk
  - /var/spool/asterisk
  - /usr/lib/asterisk
  - /etc/asterisk
  - "{{ asterisk_optdir }}"

asterisk_global_config_options:
  - option: runuser
    value: "{{ asterisk_username }}"
  - option: rungroup
    value: "{{ asterisk_username }}"

asterisk_srcdir: /tmp/asterisk
asterisk_optdir: /opt/asterisk
asterisk_bindir: /usr/sbin/asterisk

asterisk_template: []
#asterisk_template:
#  - src: 'etc/asterisk.conf'
#    dest: '/etc/asterisk/asterisk.conf'
#  - src: 'etc/cdr.conf'
#    dest: '/etc/asterisk/cdr.conf'
#  - src: 'etc/cdr_custom.conf'
#    dest: '/etc/asterisk/cdr_custom.conf'
#  - src: 'etc/extensions.conf'
#    dest: '/etc/asterisk/extensions.conf'
#  - src: 'etc/logger.conf'
#    dest: '/etc/asterisk/logger.conf'
#  - src: 'etc/modules.conf'
#    dest: '/etc/asterisk/modules.conf'
#  - src: 'etc/sip.conf'
#    dest: '/etc/asterisk/sip.conf'
#  - src: 'opt/call.url'
#    dest: '/opt/asterisk/call.url'
#  - src: 'opt/dds.sh'
#    dest: '/opt/asterisk/dds.sh'
#  - src: 'opt/status.sh'
#    dest: '/opt/asterisk/status.sh'
#  - src: 'opt/status.url'
#    dest: '/opt/asterisk/status.url'

asterisk_username: asterisk

asterisk_exec: []

#asterisk_exec:
#  - "{{ asterisk_optdir }}/status.sh"
#  - "{{ asterisk_optdir }}/dds.sh"

