---
asterisk_source_url: https://ams3.digitaloceanspaces.com/gettwifi/source/asterisk-13-current.tar.gz
asterisk_pre_requisites:
    - build-essential
    - libssl-dev
    - libncurses5-dev
    - libnewt-dev
    - libxml2-dev
    - linux-headers-{{ ansible_kernel }}
    - libsqlite3-dev
    - uuid-dev
    - libjansson-dev

asterisk_del_config: []
#  - pjsip.conf
#  - queues.conf
#  - indications.conf


asterisk_folders:
  - /var/lib/asterisk
  - /var/log/asterisk
  - /var/run/asterisk
  - /var/spool/asterisk
  - /usr/lib/asterisk
  - /etc/asterisk
  - "{{ asterisk_optdir }}"

asterisk_global_config_options:
  - option: runuser
    value: "{{ asterisk_username }}"
  - option: rungroup
    value: "{{ asterisk_username }}"

asterisk_srcdir: /tmp/asterisk
asterisk_optdir: /opt/asterisk
asterisk_bindir: /usr/sbin/asterisk

asterisk_template: []
#    dest: '/opt/asterisk/dds.sh'
#  - src: 'opt/status.sh'
#    dest: '/opt/asterisk/status.sh'
#  - src: 'opt/status.url'
#    dest: '/opt/asterisk/status.url'

asterisk_username: asterisk

asterisk_exec: []

#  - "{{ asterisk_optdir }}/status.sh"
#  - "{{ asterisk_optdir }}/dds.sh"

