---
radius_package:
  - 'freeradius=3.0.15-ppa1~xenial'

radius_depend_package:
  - 'freeradius-postgresql'
radius_config_dir: '/etc/freeradius'
radius_template: []
# radius_template:
#  - dir: mods-available
#    link: 'mods-enabled'
#    template:
#      - src: 'sql'
#        dest: 'sql'
#  - dir: mods-config
#    template:
#      - src: 'schema.sql'
#        dest: 'schema.sql'
#  - dir: sites-available
#    link: 'sites-enabled'
#    template:
#      - src: 'karma-access-points'
#        dest: 'karma-access-points'
#      - src: 'karma-users-chilli'
#        dest: 'karma-users-chilli'
#      - src: 'karma-users-cisco'
#        dest: 'karma-users-cisco'
#      - src: 'karma-users-mikrotik'
#        dest: 'karma-users-mikrotik'

radius_file: []
# radius_file:
#  - src: 'freeradius/mods-config/queries.conf'
#    dest: '/etc/freeradius/mods-config/queries.conf'

unlink_config: []
# unlink_config:
#  - '/etc/freeradius/sites-enabled/default'
#  - '/etc/freeradius/sites-enabled/inner-tunnel'
#  - '/etc/freeradius/mods-enabled/eap'

freeradius_config_options:
  - option: 'auth'
    value: 'yes'
#  - option: proxy_requests
#    value: 'no'

freeradius_include_options:
  - option: 'INCLUDE proxy.conf'
    value: '#$INCLUDE proxy.conf'
  - option: 'INCLUDE clients.conf'
    value: '#$INCLUDE clients.conf'
  - option: 'proxy_requests'
    value: 'proxy_requests  = no'

postgres_server: "{{ hostvars[groups['postgresql'][0]].ansible_ssh_host }}"
postgrs_conf:

radius_secret: "nungeiThai6ieze"

karma_users_chilli_auth_port: 17751
karma_users_chilli_acct_port: 17752
karma_users_cisco_auth_port: 17761
karma_users_cisco_acct_port: 17762
karma_users_mikrotik_auth_port: 17771
karma_users_mikrotik_acct_port: 17772
karma_access_points_auth_port: 17781
