---
radius_template:
  - src: 'freeradius/mods-available/sql'
    dest: '/etc/freeradius/mods-available/sql'
  - src: 'freeradius/mods-config/schema.sql'
    dest: '/etc/freeradius/mods-config/schema.sql'
  - src: 'freeradius/sites-available/karma-access-points'
    dest: '/etc/freeradius/sites-available/karma-access-points'
  - src: 'freeradius/sites-available/karma-users-chilli'
    dest: '/etc/freeradius/sites-available/karma-users-chilli'
  - src: 'freeradius/sites-available/karma-users-cisco'
    dest: '/etc/freeradius/sites-available/karma-users-cisco'
  - src: 'freeradius/sites-available/karma-users-mikrotik'
    dest: '/etc/freeradius/sites-available/karma-users-mikrotik'

radius_file:
  - src: 'freeradius/mods-config/queries.conf'
    dest: '/etc/freeradius/mods-config/queries.conf'

link_config:
  - src: '/etc/freeradius/sites-available/karma-access-points'
    dest: '/etc/freeradius/sites-enabled/karma-access-points'
  - src: '/etc/freeradius/sites-available/karma-users-chilli'
    dest: '/etc/freeradius/sites-enabled/karma-users-chilli'
  - src: '/etc/freeradius/sites-available/karma-users-cisco'
    dest: '/etc/freeradius/sites-enabled/karma-users-cisco'
  - src: '/etc/freeradius/sites-available/karma-users-mikrotik'
    dest: '/etc/freeradius/sites-enabled/karma-users-mikrotik'
  - src: '/etc/freeradius/mods-available/sql'
    dest: '/etc/freeradius/mods-enabled/sql'

unlink_config:
  - '/etc/freeradius/sites-enabled/default'
  - '/etc/freeradius/sites-enabled/inner-tunnel'
  - '/etc/freeradius/mods-enabled/eap'

freeradius_config_options:
  - option: 'auth'
    value: 'yes'
#  - option: proxy_requests
#    value: 'no'

freeradius_include_options:
  - option: 'INCLUDE proxy.conf'
    value: '#$INCLUDE proxy.conf'
  - option: 'INCLUDE clients.conf'
    value: '#$INCLUDE clients.conf'
  - option: 'proxy_requests'
    value: 'proxy_requests  = no'

postgres_server: "{{ groups['postgresql'][0] }}"

private_interface: eth1
interface_fact_var: ansible_{{ private_interface }}
radius_secret: "nungeiThai6ieze"

karma_users_chilli_auth_port: 17751
karma_users_chilli_acct_port: 17752
karma_users_cisco_auth_port: 17761
karma_users_cisco_acct_port: 17762
karma_users_mikrotik_auth_port: 17771
karma_users_mikrotik_acct_port: 17772

#public_port:
#  - "{{ karma_users_chilli_auth_port }}"
#  - "{{ karma_users_chilli_acct_port }}"
#  - "{{ karma_users_cisco_auth_port }}"
#  - "{{ karma_users_cisco_acct_port }}"
#  - "{{ karma_users_mikrotik_auth_port }}"
#  - "{{ karma_users_mikrotik_acct_port }}"

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: "{{ karma_users_chilli_auth_port }}"
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: "{{ karma_users_chilli_acct_port }}"
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: "{{ karma_users_cisco_auth_port }}"
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: "{{ karma_users_cisco_acct_port }}"
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: "{{ karma_users_mikrotik_auth_port }}"
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: "{{ karma_users_mikrotik_acct_port }}"
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0