---
redis_bindir: /usr/local/bin
redis_srcdir: /tmp/redis
redis_user: redis
redis_datadir: /var/lib/redis
redis_config_folder: /etc/redis
redis_log_folders: /var/log/redis
redis_source_url: https://ams3.digitaloceanspaces.com/gettwifi/source/redis-4.0.11.tar.gz

redis_configs:
  - redis.conf
  - sentinel.conf

redis_global_config_options:
  - option: supervised
    value: 'systemd'
  - option: dir
    value: '{{ redis_datadir }}'
  - option: logfile
    value: '{{ redis_log_folders }}/redis-server.log'
  - option: protected-mode
    value: 'no'
  - option: bind
    value: '{{ ansible_ssh_host }} 127.0.0.1'

redis_slave_config_options:
  - option: slaveof
    value: "{{ hostvars[groups['redis'][0]].ansible_ssh_host }} 6379"

sentinel_global_config_options:
  - option: bind
    value: '{{ ansible_ssh_host }} 127.0.0.1'
  - option: supervised
    value: 'systemd'
  - option: daemonize
    value: 'no'
  - option: logfile
    value: '{{ redis_log_folders }}/redis-sentinel.log'
  - option: protected-mode
    value: 'no'
  - option: sentinel monitor
    value: "mymaster {{ groups['redis'][0] }} 6379 2"
  - option: sentinel failover-timeout
    value: "mymaster 10000"
  - option: sentinel down-after-milliseconds
    value: "mymaster 5000"
#  - option: sentinel myid
#    value: "11883c15aff687915cfea6d8e00a16ffd1b23f7e"

recreate_cluster: false

redis_build_package:
  - build-essential
  - tcl
