---
- name: set ViM as default editor
  alternatives:
    name: editor
    path: "{{ defaults.editor }}"

- name: set timezone to Europe/Moscow
  timezone:
    name: "{{ defaults.timezone }}"
  notify: restart rsyslog

- name: Ensure a RU locale exists
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales }}"
