---
- name: Install common programm
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  with_items:
    - git
    - vim       
    - gzip
    - wget    
    - curl    
    - unzip
    - zip
    - htop
    - iotop
    - nload
    - iftop
    - screen
    - apt-transport-https
    - dmidecode
    - gnupg
    - build-essential
    - libcurl4-openssl-dev
    - ca-certificates 
    - software-properties-common 
    - imagemagick 
    - tzdata 
    - ntp

- name: set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow
  notify: restart rsyslog


 



