---
- name: fetch netplan file from server
  fetch:
    src: "/etc/netplan/{{ netplan_config }}"
    dest: "/tmp/{{ inventory_hostname }}{{ netplan_config }}"
    flat: true
  changed_when: false

- name: load netplan file
  include_vars:
    file: "/tmp/{{ inventory_hostname }}{{ netplan_config }}"
    name: cloud

# - debug:
#    msg: "{{ item }}"
#  with_items: "{{ cloud.network.ethernets.eth0.nameservers.addresses[0] }}"

- name: edit netpaln config file for all servers
  lineinfile:
    backup: true
    path: "/etc/netplan/{{ netplan_config }}"
    regexp: "{{ item.path }}"
    line: "{{ item.regexp }}"
  with_items:
    - { path: "^.*{{ cloud.network.ethernets.eth0.nameservers.addresses[0] }}", regexp: "                - {{ groups['dns'][0] }}" }
    - { path: "^.*{{ cloud.network.ethernets.eth0.nameservers.addresses[1] }}", regexp: "                - {{ groups['dns'][0] }}" }
  when: cloud.network.ethernets.eth0.nameservers.addresses[0] != groups['dns'][0] and inventory_hostname != groups['dns'][0]
  notify: netplan apply

- name: edit netpaln config file for dns server
  lineinfile:
    backup: true
    path: "/etc/netplan/{{ netplan_config }}"
    regexp: "{{ item.path }}"
    line: "{{ item.regexp }}"
  with_items:
    - { path: "^.*{{ cloud.network.ethernets.eth0.nameservers.addresses[0] }}", regexp: "                - 127.0.0.1" }
  when: cloud.network.ethernets.eth0.nameservers.addresses[0] != '127.0.0.1' and inventory_hostname == groups['dns'][0]
  notify: netplan apply

- name: validate netpaln conf
  command: netplan try --timeout 0
  changed_when: false

- name: netplan apply
  command: netplan apply
  changed_when: false
