#  dind:
#    restart: always
#    privileged: true
#    volumes:
#    - /var/lib/docker
#    image: docker:17.09.0-ce-dind
#    command:
#    - --storage-driver=overlay2

  runner:
    restart: always
    image: gitlab/gitlab-runner:latest
    volumes:
    - /srv/gitlab-runner/config:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#    - DOCKER_HOST=tcp://dind:2375

  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:latest
    volumes:
    - /srv/gitlab-runner/config:/etc/gitlab-runner
    command:
    - register
    - --non-interactive
    - --locked=false
    - --name=Docker Runner
    - --executor=docker
    - --docker-image=alpine:latest
    - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    environment:
    - CI_SERVER_URL=https://{{ gitlab_name }}/
    - REGISTRATION_TOKEN={{ gitlab_tocken }}