---
ansible_user: root

domain: gw.lan
rev_domain: 135.10.in-addr.arpa
host_name: ns1.{{ domain }}

list_public: false

records:
  local:
    ns1:
      forward: 10.135.101.26
      type: A
      last: 26.101
      rev: 135.10.in-addr.arpa
    zabbix:
      forward: 10.135.56.169
      type: A
      last: 169.56
      rev: 135.10.in-addr.arpa
    runner1:
      forward: 10.135.94.37
      type: A
      last: 37.94
      rev: 135.10.in-addr.arpa
    db-master:
      forward: 10.135.72.192
      type: A
      last: 192.72
      rev: 135.10.in-addr.arpa
    db-slave:
      forward: 10.135.20.228
      type: A
      last: 228.20
      rev: 135.10.in-addr.arpa
    openvpn1:
      forward: 10.135.16.158
      type: A
      last: 158.16
      rev: 135.10.in-addr.arpa

  gettwifi:
    "@":
      forward: 10.135.11.170
      type: A
      last: 170.11
      rev: 135.10.in-addr.arpa

zones:
  local:
    name: gw.lan
  gettwifi:
    name: gitlab.gettwifi.com

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
  - rule: 'allow'
    port: 53
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 53
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 10050
    proto: 'tcp'
    from_ip: "{{ groups['zabbix'] }}"
    to_ip: "{{ inventory_hostname }}"