---
rvm1_user: root
rvm1_install_path: /usr/local/rvm
rvm1_install_flags: '--auto-dotfiles'

create_user: true
local_user:
  - name: web
    group: www-data
    password: 1128256asdf
    password_lock: yes
    home: /opt/www
    shell: /bin/bash
    groups:
      - rvm

ufw_reset: true

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
  - rule: 'allow'
    port: 443
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
  - rule: 'allow'
    port: 80
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0