---
- name: add repository for cassandra
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present

- name: add key for docker repositories
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.id }}"
    state: present
  with_items: "{{ docker_key }}"

- name: Install common docker package
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - docker-engine
    - python-setuptools
    - python-pip

- name: install docker python
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose
