---
- name: add docker key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add repository for docker
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present
#    validate_certs: no

#- name: add key for docker repositories
#  apt_key:
#    keyserver: "{{ item.keyserver }}"
#    id: "{{ item.id }}"
#    state: present
#  with_items: "{{ docker_key }}"

- name: Install common docker package
  apt:
    name: "{{ item }}"
    update_cache: yes
#    state: latest
  with_items:
    - docker-ce
    - python-setuptools
    - python-pip

- name: install docker python
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose

- include_tasks: "registrator.yml"
  when: consul_docker_registrator
