---
- name: Install required package
  apt:
    name: "gnupg"
    update_cache: true

- name: add docker key
  apt_key:
    url: "{{ docker_key }}"
    state: present

- name: add repository for docker
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present

- name: Install common docker package
  apt:
    name: "{{ docker_package }}"
    update_cache: true

- name: install docker python
  pip:
    name: "{{ docker_pip_package }}"

- include_tasks: "registrator.yml"
  when: consul_docker_registrator
