---
ansible_user: root

domain: gw.lan
rev_domain: 135.10.in-addr.arpa
host_name: ns1.{{ domain }}

list_public: false

records:
  local:
    ns1:
      forward: 10.135.1.24
      type: A
      last: 24.1
      rev: 135.10.in-addr.arpa
    zabbix:
      forward: 10.135.81.75
      type: A
      last: 75.81
      rev: 135.10.in-addr.arpa
    runner1:
      forward: 10.135.8.173
      type: A
      last: 173.8
      rev: 135.10.in-addr.arpa

  gettwifi:
    "@":
      forward: 10.135.55.36
      type: A
      last: 36.55
      rev: 135.10.in-addr.arpa

zones:
  local:
    name: gw.lan
  gettwifi:
    name: gitlab.gettwifi.com

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
  - rule: 'allow'
    port: 53
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 53
    proto: 'udp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ inventory_hostname }}"