---
- name: Download asterisk source
  get_url:
    url: https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-13-current.tar.gz
    dest: /tmp/asterisk-13-current.tar.gz
    mode: 0740

- name: Extract pg_partman
  unarchive:
    src: /tmp/v3.1.1.tar.gz
    dest: /tmp
    remote_src: yes
  when: pg_partman_available.stat.exists == false

- name: Install pg_partman
  shell: cd /tmp/pg_partman-3.1.1 && make install
  when: pg_partman_available.stat.exists == false