---
softether_srcdir: vpnserver
softether_bindir: /usr/local
softether_reinstall: false

softether_source_url: https://ams3.digitaloceanspaces.com/gettwifi-src/softether-vpnserver-v4.27-9668-beta-2018.05.29-linux-x64-64bit.tar.gz

softether_template:
  - src: 'vpnserver.service'
    dest: '/lib/systemd/system/vpnserver.service'
  - src: 'tap'
    dest: '/etc/network/interfaces.d/'

softether_config: []

# softether_config:
#  - src: 'vpn_server.config'
#    dest: '/usr/local/{{ softether_srcdir }}'
