---
softether_srcdir: vpnserver

softether_source_url: https://ams3.digitaloceanspaces.com/gettwifi/source/softether-vpnserver-v4.27-9668-beta-2018.05.29-linux-x64-64bit.tar.gz

softether_template:
  - src: 'vpnserver.service'
    dest: '/lib/systemd/system/vpnserver.service'