---
softether_srcdir: vpnserver
#softether_template:
#  - src: 'vpnserver'
#    dest: '/etc/init.d/vpnserver'

softether_template:
  - src: 'vpnserver.service'
    dest: '/lib/systemd/system/vpnserver.service'