---
- name: copy zabbix user parameter for mysql
  template:
    src: userparameter_mysql.conf.j2
    dest: "{{ zabbix_conf_directory }}/userparameter_mysql.conf"
  notify: restart zabbix

- name: create user for monitoring
  mysql_user:
    name: zabbix
    password: '{{ zabbix_mysql_pass }}'
    priv: "*.*:USAGE"
    state: present

- name: Create /etc/zabbix/.my.cnf file with zabbix credentials
  template:
    src: 'my.cnf.j2'
    dest: '/etc/zabbix/.my.cnf'
    owner: 'zabbix'
    group: 'zabbix'
    mode: '0600'
