---
- name: Copy zabbix configuration for nginx
  copy:
    src: zabbix.conf
    dest: /etc/nginx/sites-available/zabbix.conf

- name: link zabbix.conf
  file:
    src: /etc/nginx/sites-available/zabbix.conf
    dest: /etc/nginx/sites-enabled/zabbix.conf 
    state: link
    force: yes
  notify: restart nginx

- name: copy zabbix user parameter for nginx
  template:
    src: nginx_parameter.conf.j2
    dest: "{{ zabbix_conf_directory }}/nginx_parameter.conf"
  notify: restart zabbix
 
- name: copy nginx script for zabbix
  copy:
    src: php-fpm-check.sh
    dest: "{{ zabbix_script_directory }}/php-fpm-check.sh"
    owner: zabbix
    group: zabbix
    mode: 0770