---
#- name: Copy zabbix configuration for nginx
#  copy:
#    src: zabbix.conf
#    dest: "{{ nginx_configs_folder }}/sites-available/zabbix.conf"
#
#- name: link zabbix.conf
#  file:
#    src: "{{ nginx_configs_folder }}/sites-available/zabbix.conf"
#    dest: "{{ nginx_configs_folder }}/sites-enabled/zabbix.conf"
#    state: link
#    force: yes
#  notify: restart nginx

- name: copy zabbix user parameter for nginx
  template:
    src: nginx_parameter.conf.j2
    dest: "{{ zabbix_conf_directory }}/nginx_parameter.conf"
  notify: restart zabbix

- name: copy nginx script for zabbix
  copy:
    src: php-fpm-check.sh
    dest: "{{ zabbix_script_directory }}/nginx-check.sh"
    owner: zabbix
    group: zabbix
    mode: 0770