---
- name: copy zabbix user parameter for mysql
  copy:
    src: userparameter_postgresql.conf
    dest: "{{ zabbix_conf_directory }}/userparameter_postgresql.conf"
  notify: restart zabbix

- name: Configure postgres settings.
  lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_postgresql_config_options }}"
  notify: restart postgresql

- name: Ensure PostgreSQL databases are present.
  postgresql_db:
    name: zabbix
  become: true
  become_user: "{{ postgresql_user }}"

- postgresql_ext:
    name: pg_stat_statements
    db: zabbix
  become: true
  become_user: "{{ postgresql_user }}"

- postgresql_ext:
    name: pg_buffercache
    db: zabbix
  become: true
  become_user: "{{ postgresql_user }}"
