---
- name: copy zabbix user parameter for netstat
  template:
    src: zabbix_smartctl.conf.j2
    dest: "{{ zabbix_conf_directory }}/abbix_smartctl.conf"
  notify: restart zabbix

- name: copy netstat script for zabbix
  copy:
    src: smartctl-disks-discovery.pl
    dest: "{{ zabbix_script_directory }}/smartctl-disks-discovery.pl"
    owner: zabbix
    group: zabbix
    mode: 0770

- name: add scripts to sudo
  lineinfile:
    state: present
    path: /etc/sudoers
    line: "zabbix ALL=(ALL) NOPASSWD: {{ zabbix_script_directory }}/smartctl-disks-discovery.pl"