web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: '{{ gitlab_name }}'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
     external_url 'https://{{ gitlab_name }}'
     letsencrypt['enable'] = false
     nginx['ssl_certificate'] = "/var/ssl/gitlab.gettwifi.com.crt"
     nginx['ssl_certificate_key'] = "/var/ssl/gitlab.gettwifi.com.key"
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
    - '/srv/ssl:/var/ssl'