web:
  image: 'gitlab/gitlab-ee:11.7.5-ee.0'
  restart: always
  hostname: '{{ gitlab_name }}'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
     external_url 'https://{{ gitlab_name }}'
     letsencrypt['enable'] = true
     nginx['redirect_http_to_https'] = true
     gitlab_rails['time_zone'] = 'Europe/Moscow'
     gitlab_rails['backup_upload_connection'] = {
        'provider' => 'AWS',
        'region' => 'ams3',
        'aws_access_key_id' => '{{ spaces_access_key }}',
        'aws_secret_access_key' => '{{ spaces_secret_key }}',
        'endpoint'              => '{{ spaces_endpoint }}'
     }
     gitlab_rails['backup_upload_remote_directory'] = '{{ space_name }}'
     gitlab_rails['backup_keep_time'] = 1209600
     registry_external_url 'https://{{ gitlab_name }}:{{ gitlab_registry_port }}'
     nginx['custom_gitlab_server_config'] = "allow 10.135.0.0/16;
       allow all;

       location ^~ /.well-known {
           root /opt/gitlab/embedded/service/gitlab-rails/public;
           allow all;
       }
       "
     nginx['real_ip_trusted_addresses'] = [ '10.135.0.0/16' ]
     nginx['real_ip_header'] = 'X-Real-IP'
     nginx['real_ip_recursive'] = 'on'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
    - "{{ gitlab_registry_port }}:{{ gitlab_registry_port }}"
  volumes:
    - '/etc/localtime:/etc/localtime'
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
    - '/srv/{{ gitlab_cert_source }}:/var/ssl'