---
- name: Copy ssl cert for gitlab
  copy:
    src: "{{ gitlab_cert_source }}"
    dest: /srv

- name: Copy site configuration
  template:
    src: docker-compose.yml
    dest: ~/docker-compose.yml

- name: build and start docker containers
  docker_service:
    project_src: /root
    build: yes
    restarted: true