---
web_user: node
local_user:
  - name: node
    group: www-data
    password: 1128256asdf
#    password_lock: yes
    home: /home/node
    shell: /bin/bash
#    allow_key:
    groups:
      - sudo

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
  - rule: 'allow'
    port: 443
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
  - rule: 'allow'
    port: 80
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
  - rule: 'allow'
    port: 10050
    proto: 'tcp'
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ ansible_ssh_host }}"

#virtualhost:
#  www:
#    url: krispykreme.gettwifi.com
#    dir: "/home/node/gettwifi---krispy-kreme/dist"
#    upstream_proxy: "krispykreme_upstream"
#    upstream_proxy_port: 3000
#    upstream_proxy_location: "/"
#    index_file: index.php
#    ssl_cert: "krispykreme.gettwifi.com"
#  www2:
#    url: test.gettwifi.com
#    dir: "/home/node/www/statistic-dashboard/build"
#    index_file: index.html
#    upstream_proxy: "test_upstream"
#    upstream_proxy_port: 4000
#    upstream_proxy_location: "/graphql"
#    ssl_cert: "test.gettwifi.com"
#  www3:
#    url: camera.gettwifi.com
##    dir: "/home/node/www/statistic-dashboard/build"
#    index_file: index.html
#    upstream_proxy: "camera_upstream"
#    upstream_proxy_port: 5000
#    upstream_proxy_location: "/snapshot"
#  www4:
#    url: export.gettwifi.com
#    dir: "/home/node/www/export-service/public"
#    index_file: index.html
#    upstream_proxy: "export_upstream"
#    upstream_proxy_port: 6000
#    upstream_proxy_location: "/"
#    ssl_cert: "export.gettwifi.com"
#  www5:
#    url: dashboard.gettwifi.com
#    dir: "/home/node/www/statistic-dashboard/build"
#    index_file: index.html
#    upstream_proxy: "dashboard_upstream"
#    upstream_proxy_port: 4000
#    upstream_proxy_location: "/graphql"
#    ssl_cert: "dashboard.gettwifi.com"
