---

ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
#      - "{{ hostvars[groups['openvpn'][0]].private_ip }}"
      - 10.135.0.0/16
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 6379
    proto: 'tcp'
#    from_ip: "{{ [groups['redis'], groups['web'], hostvars[groups['openvpn'][0]].private_ip] |flatten }}"
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 26379
    proto: 'tcp'
#    from_ip: "{{ [groups['redis'], groups['web'], hostvars[groups['openvpn'][0]].private_ip] |flatten }}"
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ inventory_hostname }}"
  - rule: 'allow'
    port: 10050
    proto: 'tcp'
#    from_ip: "{{ groups['zabbix'] }}"
    from_ip:
      - 10.135.0.0/16
    to_ip: "{{ inventory_hostname }}"
