---
passenger_nginx_dir: /opt/nginx
nginx_configs_folder: "{{ passenger_nginx_dir }}/conf"
nginx_bindir: /usr/sbin
passenger_template:
  #  - src: 'nginx'
  #    dest: '/etc/init.d/nginx'
  - src: 'nginx.service'
    dest: '/lib/systemd/system/nginx.service'
  - src: 'nginx.conf.j2'
    dest: "{{ passenger_nginx_dir }}/conf/nginx.conf"

nginx_global_config_options:
  - option: user
    value: "{{ web_user }}"
  - option: pid
    value: '/run/nginx.pid'
  - option: worker_processes
    value: 'auto'
#  - option: error_log
#    value: '/var/log/nginx/error.log'
#  - option: access_log
#    value: '/var/log/nginx/access.log'

nginx_dir:
  - /var/log/nginx

web_user: www-data
update_nginx: false

passenger_required:
  - libcurl4-openssl-dev
  - libssl-dev

zabbix_nginx_vts: true
