---
ufw_rules:
  - rule: 'allow'
    port: 22
    proto: 'tcp'
    from_ip:
      - 0.0.0.0/0
    to_ip: "{{ ansible_ssh_host }}"

##########################POSTGRESQL
postgresrep_role: skip

postgresql_users:
  - name: "{{ hotspot_user }}"
    password: "{{ hotspot_user_pass }}"
  - name: "{{ radius_user }}"
    password: "{{ radius_user_pass }}"

postgresql_databases:
  - name: hotspot
    owner: "{{ hotspot_user }}"
  - name: radius_users_mikrotik
    owner: "{{ radius_user }}"
  - name: radius_users_cisco
    owner: "{{ radius_user }}"
  - name: radius_users_chilli
    owner: "{{ radius_user }}"
  - name: radius_access_points
    owner: "{{ radius_user }}"

postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: listen_addresses
    value: 'localhost'
  - option: shared_buffers
    value: '{{ (ansible_memtotal_mb * 0.25)|int|abs }}MB'
  - option: max_connections
    value: '1000'
  - option: shared_preload_libraries
    value: 'pg_partman_bgw'
  - option: pg_partman_bgw.interval
    value: '3600'
  - option: pg_partman_bgw.dbname
    value: 'hotspot'
  - option: effective_io_concurrency
    value: '6'
  - option: seq_page_cost
    value: '1.0'
  - option: random_page_cost
    value: '2.0'

monit_template:
  - dir: conf-available
    link: 'conf-enabled'
    template:
      - src: 'monit-postgresql.conf'
        dest: 'postgresql.conf'
      - src: 'monit-freeradius.conf'
        dest: 'freeradius.conf'

########################ASTERISK

asterisk_optdir: /opt/asterisk

asterisk_template:
  - src: 'etc/asterisk.conf'
    dest: '/etc/asterisk/asterisk.conf'
  - src: 'etc/cdr.conf'
    dest: '/etc/asterisk/cdr.conf'
  - src: 'etc/cdr_custom.conf'
    dest: '/etc/asterisk/cdr_custom.conf'
  - src: 'etc/extensions.conf'
    dest: '/etc/asterisk/extensions.conf'
  - src: 'etc/logger.conf'
    dest: '/etc/asterisk/logger.conf'
  - src: 'etc/modules.conf'
    dest: '/etc/asterisk/modules.conf'
  - src: 'etc/sip.conf'
    dest: '/etc/asterisk/sip.conf'
  - src: 'opt/call.url'
    dest: '{{ asterisk_optdir }}/call.url'
  - src: 'opt/dds.sh'
    dest: '{{ asterisk_optdir }}/dds.sh'
  - src: 'opt/status.sh'
    dest: '{{ asterisk_optdir }}/status.sh'
  - src: 'opt/status.url'
    dest: '{{ asterisk_optdir }}/status.url'

asterisk_del_config:
  - pjsip.conf
  - queues.conf
  - indications.conf
  - confbridge.conf
  - voicemail.conf
  - musiconhold.conf

asterisk_exec:
  - file: "{{ asterisk_optdir }}/status.sh"
    name: "Check Asterisk trunks"
    job: "{{ asterisk_optdir }}/status.sh >> /var/log/asterisk/status.log 2>&1"
  - file: "{{ asterisk_optdir }}/dds.sh"
    name: "Check Asterisk balance movement"
    minute: "0"
    hour: "5"
    day: "1"
    job: "{{ asterisk_optdir }}/dds.sh >> /var/log/asterisk/dds.log 2>&1"


#####################RADIUS
postgres_server: localhost
postgrs_conf: "{{ inventory_dir }}/group_vars/full/vault.yml"
radius_template:
  - dir: mods-available
    link: 'mods-enabled'
    template:
      - src: 'sql'
        dest: 'sql'
  - dir: mods-config
    template:
      - src: 'schema.sql'
        dest: 'schema.sql'
  - dir: sites-available
    link: 'sites-enabled'
    template:
      - src: 'karma-access-points'
        dest: 'karma-access-points'
      - src: 'karma-users-chilli'
        dest: 'karma-users-chilli'
      - src: 'karma-users-cisco'
        dest: 'karma-users-cisco'
      - src: 'karma-users-mikrotik'
        dest: 'karma-users-mikrotik'

unlink_config:
  - '/etc/freeradius/sites-enabled/default'
  - '/etc/freeradius/sites-enabled/inner-tunnel'
  - '/etc/freeradius/mods-enabled/eap'

radius_file:
  - src: 'freeradius/mods-config/queries.conf'
    dest: '/etc/freeradius/mods-config/queries.conf'

karma_users_chilli_auth_port: 17751
karma_users_chilli_acct_port: 17752
karma_users_cisco_auth_port: 17761
karma_users_cisco_acct_port: 17762
karma_users_mikrotik_auth_port: 17771
karma_users_mikrotik_acct_port: 17772

#monit_template:
#  - dir: conf-available
#    link: 'conf-enabled'
#    template:
#      - src: 'monit-freeradius.conf'
#        dest: 'freeradius.conf'

#################REDIS

redis_configs:
  - redis.conf

redis_global_config_options:
  - option: supervised
    value: 'systemd'
  - option: dir
    value: '{{ redis_datadir }}'
  - option: logfile
    value: '{{ redis_log_folders }}/redis-server.log'
  - option: protected-mode
    value: 'no'
  - option: bind
    value: '127.0.0.1'

redis_slave_config_options: []
sentinel_global_config_options: []

#####################CASSANDRA

cassandra_global_config_options: []

#####################RVM

rvm1_user: root
rvm1_install_path: /usr/local/rvm
rvm1_install_flags: '--auto-dotfiles'

create_user: true
local_user:
  - name: web
    group: www-data
    password: 1128256asdf
    password_lock: yes
    home: /opt/www
    shell: /bin/bash
    groups:
      - rvm